### ISSUE TITLE
Use more than two robots may cause Errors!

### ISSUE THREAD

**Issue by BlueBirdHouse** [jdelacroix/simiam#12]
Use more than two robots may cause Errors!
when use more than 3 Khepera3 robots block in the simulink environment,the software may run into an error.
Because by default, In file:
+simiam\ControlAPP.m in line:
 function obj = ControlApp(root)
obj.supervisors = simiam.containers.ArrayList(2);
The array list only accept 2 supervisors.
This will make the file:
anApp.supervisors.appendElement(supervisor);
in +simiam\Words.m Error.

**Comment by jdelacroix** [comment]
Agreed; however, ControlApp.m (or any other app) should always be adjusted along with the addition of more robots to settings.xml. The current ControlApp.m is provided as an example of how to work with two robots only.
