### ISSUE TITLE
Error when connecting to simiam to BBB

### ISSUE THREAD

**Issue by tho15** [jdelacroix/simiam#14]
Hi,

When I try to connect simiam to BBB quickbot, I get following error:

Error using javaObject
No class java.edu.gatech.gritslab.QuickBotConnector can be located on the Java class path

Error in simiam.robot.driver.QuickBotDriver (line 30)
            obj.java_handle = javaObject('java.edu.gatech.gritslab.QuickBotConnector',
            hostname, port);

Error in simiam.robot.QuickBot/add_hardware_link (line 217)
            obj.driver = simiam.robot.driver.QuickBotDriver(hostname, port);

Error in simiam.simulator.World/build_from_file (line 59)
                       r.add_hardware_link(hostname,port);

Error in simiam.ui.AppWindow/create_simulator (line 81)
            world.build_from_file(obj.root_, settings_file, obj.origin_);

Error in simiam.ui.AppWindow/ui_button_start (line 346)
            obj.create_simulator(fullfile(obj.root_, 'settings.xml'));

Error in simiam.ui.AppWindow>@(varargin)obj.ui_button_start(varargin{:}) (line 143)
            ui_args = {'Style','pushbutton', 'ForegroundColor', 'w', 'FontWeight', 'bold',
            'Callback', @obj.ui_button_start};

Error while evaluating uicontrol Callback

Try to add java path to Matlab, but still get the same error. My Matlab version is 12b. Any help will be highly appreciated.

**Comment by jdelacroix** [comment]
Make sure to recompile QuickBotConnector.java in the java/ directory using the Java compiler: javac QuickBotConnector.java
