### ISSUE TITLE
Compatible with v2 Quickbot?

### ISSUE THREAD

**Issue by fsteveb** [jdelacroix/simiam#18]
I'm in the course and saw there is a new version of the bot. It looks like all the comments I've seen reference V1. I'll build the V2 unless it doesn't work with the current simulator.

**Comment by jdelacroix** [comment]
We tested the simulator against V2, and it worked. However, you may have to adjust a few variables in the QuickBot.m file that relate to the wheel encoders and RPM ranges of the motors.
